services:
  db:
    image: postgres:16
    container_name: mrp_postgres
    environment:
      POSTGRES_DB: mrp
      POSTGRES_USER: mrp_user
      POSTGRES_PASSWORD: mrp_pass
    ports:
      - "5432:5432"
    volumes:
      - mrp_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mrp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: if24b029@technikum-wien.at
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - mrp_pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  mrp_pgdata:
  mrp_pgadmin:
